# Generated by Django 4.2.13 on 2024-12-13 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='owner',
        ),
    ]
