# Generated by Django 4.2.13 on 2024-12-14 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_rename_user_post_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='id',
        ),
    ]
