# Generated by Django 4.2.13 on 2024-12-14 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_rename_postid_post_id_rename_userid_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='postID',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='userID',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('likeID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.post')),
            ],
        ),
    ]
