# Generated by Django 4.2.13 on 2024-12-14 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_rename_likeid_like_id_rename_postid_post_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='id',
            new_name='likeid',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='postid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='userid',
        ),
    ]
