# Generated by Django 4.2.13 on 2024-12-15 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_rename_post_like_postid_rename_user_like_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastactive',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('followid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('followedid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed', to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
