# Generated by Django 4.2.17 on 2024-12-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_follow_follower_follow_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
